FROM openjdk:17-jdk-bullseye
RUN apt-get update && apt-get install -y wget unzip
RUN wget https://github.com/JetBrains/kotlin/releases/download/v1.9.24/kotlin-compiler-1.9.24.zip -O /tmp/kotlin.zip \
    && unzip /tmp/kotlin.zip -d /opt \
    && rm /tmp/kotlin.zip
ENV PATH="/opt/kotlinc/bin:${PATH}"
WORKDIR /app
CMD ["/bin/sh", "-c", "kotlinc program.kt -include-runtime -d program.jar && java -jar program.jar"]